language: node_js

sudo: false

node_js:
  - "4.2.1"

after_success:
  - |
        curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/huytrinh/movietitletranslator/trigger/$DOCKER_HUB_TRIGGER/